### ISSUE TITLE
react-router-v1-beta

### ISSUE THREAD

**Issue by eriknyk** [LegitTalon/fluxible-plugin-react-router#3]
did you try use your plugin for react-router 1.0.0.-beta2 ?

Regards.

**Comment by marnusw** [comment]
Not sure if @LegitTalon has; I haven't yet, but it's on my to-do list. I see they have the documentation for it up on the react-router site which will help. I don't think much, if anything, would have to change on the plugin, do you have any specific concerns that you can point out to us in the mean time?

**Comment by LegitTalon** [comment]
As I understand it the only thing that would break this plugin is if the `.run` method on React Router was deprecated or renamed which I suspect is extremely unlikely. Otherwise the only thing this plugin does is know how to tell Fluxible to have the router.

@eriknyk tl;dr: It'll work.

**Comment by jeffreywescott** [comment]
@LegitTalon ... ummm, I think .run() is no longer a part of react-router ... Routes are now just a component that gets rendered.

***WARNING:*** I'm new to react-router, so I may be misunderstanding something.

**Comment by marnusw** [comment]
We'll continue this discussion in #4.
