### ISSUE TITLE
Async-fetching data on server side?

### ISSUE THREAD

**Issue by x1a0** [LegitTalon/fluxible-plugin-react-router#4]
Hi,

Maybe this is off topic here. Does this plugin provide a standard way/pattern to fetching data that are required for rendering on server side?

**Comment by marnusw** [comment]
Indeed, way off topic. The answer is no, but, you can check out [marnusw/fluxible-plugin-store-execute-action](https://github.com/marnusw/fluxible-plugin-store-execute-action#usage).
